[package]
name = "entity"
version = "0.1.0"
edition = "2021"
authors = ["Anson VanDoren <anson@ansonvandoren.com>"]
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }

[dependencies.sea-orm]
version = "0.12.6"